// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imkpavcahkvtaqcozema.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlta3BhdmNhaGt2dGFxY296ZW1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NDc5OTQsImV4cCI6MjA2MTUyMzk5NH0.Asdy9TtMSYfVFrhORAB0AN7U9yTi6L9NkFb_N7vfeWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);